name: "Build and test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: eslint
        run: npx eslint

      - name: Ensure no pending Git changes
        run: |
          GIT_STATUS=$(git status --porcelain)
          if [[ -n $GIT_STATUS ]]; then
            echo "There are pending Git changes after running the build. Did you forget to commit the .js files?"
            echo "$GIT_STATUS"
            exit 1
          fi

      - name: Run unit tests
        run: npm run test

      - uses: "./.github/shared/functional-tests"
